apiVersion: apps/v1
kind: Deployment
metadata:
  name: storybook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
        storybook: web
  template:
    metadata:
      labels:
        storybook: web
    spec:
      containers:
      - name: storybook-site
        image: storybook_app
---
apiVersion: v1
kind: Service
metadata:
  name: storybook-entrypoint
  namespace: default
spec:
  selector:
    storybook: web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
  type: NodePort
    